# This is a basic workflow to help you get started with Actions
#${{github.workspace}}\BlankProcess4\UiPathAnalyzeProject.ps1 ${{github.workspace}}\BlankProcess4\project.json -analyzerTraceLevel "Info" -stopOnRuleViolation true -treatWarningsAsErrors false -resultPath "${{github.workspace}}\BlankProcess4\output.json" -uipathCliFilePath "${{github.workspace}}\BlankProcess4\UiPath.CLI.Windows.23.10.8753.32995 (1)\tools\uipcli.exe" -orchestratorUrl "https://staging.uipath.com" -orchestratorAccountForApp "tamcontieri" -orchestratorTenant DefaultTenant -orchestratorApplicationId "d1fb1f0a-5e14-4e54-ba83-7370f9942846" -orchestratorApplicationSecret "wHt~sMKc05LvLphF" -orchestratorApplicationScope "OR.Administration OR.Analytics OR.Assets OR.Audit OR.BackgroundTasks OR.Execution OR.Folders OR.Hypervisor OR.Jobs OR.License OR.Machines OR.ML OR.Monitoring OR.Queues OR.Robots OR.Robots.Read OR.Settings OR.Tasks OR.TestDataQueues OR.TestSetExecutions OR.TestSets OR.TestSetSchedules OR.Users OR.Webhooks"  -orchestratorFolder Shared
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cleaner:
    runs-on:  windows-2019
    steps:
      - name: Runner workspace path
        run: |
          tnc staging.uipath.com
          tnc google.com
          invoke-RestMethod 'https://catfact.ninja/fact' -Method 'GET'
          echo ${{github.workspace}}




  analyze-project:
    needs: cleaner
    runs-on: windows-2019
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v3
      - name: Analyze project for errors  
        shell:  pwsh
        run: ${{github.workspace}}\BlankProcess4\GetToken.ps1

    
       
